package nl.dronexpert.wildfiremapper.data.protobuf;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotspot_message.proto

public final class HotspotMessageProto {
  private HotspotMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HotspotOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Hotspot)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.DroneInfo drone_info = 1;</code>
     */
    boolean hasDroneInfo();
    /**
     * <code>.DroneInfo drone_info = 1;</code>
     */
    HotspotMessageProto.DroneInfo getDroneInfo();
    /**
     * <code>.DroneInfo drone_info = 1;</code>
     */
    HotspotMessageProto.DroneInfoOrBuilder getDroneInfoOrBuilder();

    /**
     * <code>.Location location = 2;</code>
     */
    boolean hasLocation();
    /**
     * <code>.Location location = 2;</code>
     */
    HotspotMessageProto.Location getLocation();
    /**
     * <code>.Location location = 2;</code>
     */
    HotspotMessageProto.LocationOrBuilder getLocationOrBuilder();

    /**
     * <code>double temperature = 3;</code>
     */
    double getTemperature();
  }
  /**
   * Protobuf type {@code Hotspot}
   */
  public  static final class Hotspot extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Hotspot)
      HotspotOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Hotspot.newBuilder() to construct.
    private Hotspot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Hotspot() {
      temperature_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Hotspot(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              HotspotMessageProto.DroneInfo.Builder subBuilder = null;
              if (droneInfo_ != null) {
                subBuilder = droneInfo_.toBuilder();
              }
              droneInfo_ = input.readMessage(HotspotMessageProto.DroneInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(droneInfo_);
                droneInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              HotspotMessageProto.Location.Builder subBuilder = null;
              if (location_ != null) {
                subBuilder = location_.toBuilder();
              }
              location_ = input.readMessage(HotspotMessageProto.Location.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(location_);
                location_ = subBuilder.buildPartial();
              }

              break;
            }
            case 25: {

              temperature_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HotspotMessageProto.internal_static_Hotspot_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HotspotMessageProto.internal_static_Hotspot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HotspotMessageProto.Hotspot.class, HotspotMessageProto.Hotspot.Builder.class);
    }

    public static final int DRONE_INFO_FIELD_NUMBER = 1;
    private HotspotMessageProto.DroneInfo droneInfo_;
    /**
     * <code>.DroneInfo drone_info = 1;</code>
     */
    public boolean hasDroneInfo() {
      return droneInfo_ != null;
    }
    /**
     * <code>.DroneInfo drone_info = 1;</code>
     */
    public HotspotMessageProto.DroneInfo getDroneInfo() {
      return droneInfo_ == null ? HotspotMessageProto.DroneInfo.getDefaultInstance() : droneInfo_;
    }
    /**
     * <code>.DroneInfo drone_info = 1;</code>
     */
    public HotspotMessageProto.DroneInfoOrBuilder getDroneInfoOrBuilder() {
      return getDroneInfo();
    }

    public static final int LOCATION_FIELD_NUMBER = 2;
    private HotspotMessageProto.Location location_;
    /**
     * <code>.Location location = 2;</code>
     */
    public boolean hasLocation() {
      return location_ != null;
    }
    /**
     * <code>.Location location = 2;</code>
     */
    public HotspotMessageProto.Location getLocation() {
      return location_ == null ? HotspotMessageProto.Location.getDefaultInstance() : location_;
    }
    /**
     * <code>.Location location = 2;</code>
     */
    public HotspotMessageProto.LocationOrBuilder getLocationOrBuilder() {
      return getLocation();
    }

    public static final int TEMPERATURE_FIELD_NUMBER = 3;
    private double temperature_;
    /**
     * <code>double temperature = 3;</code>
     */
    public double getTemperature() {
      return temperature_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (droneInfo_ != null) {
        output.writeMessage(1, getDroneInfo());
      }
      if (location_ != null) {
        output.writeMessage(2, getLocation());
      }
      if (temperature_ != 0D) {
        output.writeDouble(3, temperature_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (droneInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDroneInfo());
      }
      if (location_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLocation());
      }
      if (temperature_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, temperature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HotspotMessageProto.Hotspot)) {
        return super.equals(obj);
      }
      HotspotMessageProto.Hotspot other = (HotspotMessageProto.Hotspot) obj;

      boolean result = true;
      result = result && (hasDroneInfo() == other.hasDroneInfo());
      if (hasDroneInfo()) {
        result = result && getDroneInfo()
            .equals(other.getDroneInfo());
      }
      result = result && (hasLocation() == other.hasLocation());
      if (hasLocation()) {
        result = result && getLocation()
            .equals(other.getLocation());
      }
      result = result && (
          java.lang.Double.doubleToLongBits(getTemperature())
          == java.lang.Double.doubleToLongBits(
              other.getTemperature()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDroneInfo()) {
        hash = (37 * hash) + DRONE_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getDroneInfo().hashCode();
      }
      if (hasLocation()) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocation().hashCode();
      }
      hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTemperature()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HotspotMessageProto.Hotspot parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HotspotMessageProto.Hotspot parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HotspotMessageProto.Hotspot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HotspotMessageProto.Hotspot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HotspotMessageProto.Hotspot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HotspotMessageProto.Hotspot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HotspotMessageProto.Hotspot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HotspotMessageProto.Hotspot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HotspotMessageProto.Hotspot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HotspotMessageProto.Hotspot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HotspotMessageProto.Hotspot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HotspotMessageProto.Hotspot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HotspotMessageProto.Hotspot prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Hotspot}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Hotspot)
        HotspotMessageProto.HotspotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HotspotMessageProto.internal_static_Hotspot_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HotspotMessageProto.internal_static_Hotspot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HotspotMessageProto.Hotspot.class, HotspotMessageProto.Hotspot.Builder.class);
      }

      // Construct using HotspotMessageProto.Hotspot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (droneInfoBuilder_ == null) {
          droneInfo_ = null;
        } else {
          droneInfo_ = null;
          droneInfoBuilder_ = null;
        }
        if (locationBuilder_ == null) {
          location_ = null;
        } else {
          location_ = null;
          locationBuilder_ = null;
        }
        temperature_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HotspotMessageProto.internal_static_Hotspot_descriptor;
      }

      public HotspotMessageProto.Hotspot getDefaultInstanceForType() {
        return HotspotMessageProto.Hotspot.getDefaultInstance();
      }

      public HotspotMessageProto.Hotspot build() {
        HotspotMessageProto.Hotspot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HotspotMessageProto.Hotspot buildPartial() {
        HotspotMessageProto.Hotspot result = new HotspotMessageProto.Hotspot(this);
        if (droneInfoBuilder_ == null) {
          result.droneInfo_ = droneInfo_;
        } else {
          result.droneInfo_ = droneInfoBuilder_.build();
        }
        if (locationBuilder_ == null) {
          result.location_ = location_;
        } else {
          result.location_ = locationBuilder_.build();
        }
        result.temperature_ = temperature_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HotspotMessageProto.Hotspot) {
          return mergeFrom((HotspotMessageProto.Hotspot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HotspotMessageProto.Hotspot other) {
        if (other == HotspotMessageProto.Hotspot.getDefaultInstance()) return this;
        if (other.hasDroneInfo()) {
          mergeDroneInfo(other.getDroneInfo());
        }
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        if (other.getTemperature() != 0D) {
          setTemperature(other.getTemperature());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HotspotMessageProto.Hotspot parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HotspotMessageProto.Hotspot) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private HotspotMessageProto.DroneInfo droneInfo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          HotspotMessageProto.DroneInfo, HotspotMessageProto.DroneInfo.Builder, HotspotMessageProto.DroneInfoOrBuilder> droneInfoBuilder_;
      /**
       * <code>.DroneInfo drone_info = 1;</code>
       */
      public boolean hasDroneInfo() {
        return droneInfoBuilder_ != null || droneInfo_ != null;
      }
      /**
       * <code>.DroneInfo drone_info = 1;</code>
       */
      public HotspotMessageProto.DroneInfo getDroneInfo() {
        if (droneInfoBuilder_ == null) {
          return droneInfo_ == null ? HotspotMessageProto.DroneInfo.getDefaultInstance() : droneInfo_;
        } else {
          return droneInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.DroneInfo drone_info = 1;</code>
       */
      public Builder setDroneInfo(HotspotMessageProto.DroneInfo value) {
        if (droneInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          droneInfo_ = value;
          onChanged();
        } else {
          droneInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.DroneInfo drone_info = 1;</code>
       */
      public Builder setDroneInfo(
          HotspotMessageProto.DroneInfo.Builder builderForValue) {
        if (droneInfoBuilder_ == null) {
          droneInfo_ = builderForValue.build();
          onChanged();
        } else {
          droneInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.DroneInfo drone_info = 1;</code>
       */
      public Builder mergeDroneInfo(HotspotMessageProto.DroneInfo value) {
        if (droneInfoBuilder_ == null) {
          if (droneInfo_ != null) {
            droneInfo_ =
              HotspotMessageProto.DroneInfo.newBuilder(droneInfo_).mergeFrom(value).buildPartial();
          } else {
            droneInfo_ = value;
          }
          onChanged();
        } else {
          droneInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.DroneInfo drone_info = 1;</code>
       */
      public Builder clearDroneInfo() {
        if (droneInfoBuilder_ == null) {
          droneInfo_ = null;
          onChanged();
        } else {
          droneInfo_ = null;
          droneInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.DroneInfo drone_info = 1;</code>
       */
      public HotspotMessageProto.DroneInfo.Builder getDroneInfoBuilder() {
        
        onChanged();
        return getDroneInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.DroneInfo drone_info = 1;</code>
       */
      public HotspotMessageProto.DroneInfoOrBuilder getDroneInfoOrBuilder() {
        if (droneInfoBuilder_ != null) {
          return droneInfoBuilder_.getMessageOrBuilder();
        } else {
          return droneInfo_ == null ?
              HotspotMessageProto.DroneInfo.getDefaultInstance() : droneInfo_;
        }
      }
      /**
       * <code>.DroneInfo drone_info = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          HotspotMessageProto.DroneInfo, HotspotMessageProto.DroneInfo.Builder, HotspotMessageProto.DroneInfoOrBuilder> 
          getDroneInfoFieldBuilder() {
        if (droneInfoBuilder_ == null) {
          droneInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              HotspotMessageProto.DroneInfo, HotspotMessageProto.DroneInfo.Builder, HotspotMessageProto.DroneInfoOrBuilder>(
                  getDroneInfo(),
                  getParentForChildren(),
                  isClean());
          droneInfo_ = null;
        }
        return droneInfoBuilder_;
      }

      private HotspotMessageProto.Location location_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          HotspotMessageProto.Location, HotspotMessageProto.Location.Builder, HotspotMessageProto.LocationOrBuilder> locationBuilder_;
      /**
       * <code>.Location location = 2;</code>
       */
      public boolean hasLocation() {
        return locationBuilder_ != null || location_ != null;
      }
      /**
       * <code>.Location location = 2;</code>
       */
      public HotspotMessageProto.Location getLocation() {
        if (locationBuilder_ == null) {
          return location_ == null ? HotspotMessageProto.Location.getDefaultInstance() : location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>.Location location = 2;</code>
       */
      public Builder setLocation(HotspotMessageProto.Location value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
          onChanged();
        } else {
          locationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Location location = 2;</code>
       */
      public Builder setLocation(
          HotspotMessageProto.Location.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
          onChanged();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Location location = 2;</code>
       */
      public Builder mergeLocation(HotspotMessageProto.Location value) {
        if (locationBuilder_ == null) {
          if (location_ != null) {
            location_ =
              HotspotMessageProto.Location.newBuilder(location_).mergeFrom(value).buildPartial();
          } else {
            location_ = value;
          }
          onChanged();
        } else {
          locationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Location location = 2;</code>
       */
      public Builder clearLocation() {
        if (locationBuilder_ == null) {
          location_ = null;
          onChanged();
        } else {
          location_ = null;
          locationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Location location = 2;</code>
       */
      public HotspotMessageProto.Location.Builder getLocationBuilder() {
        
        onChanged();
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>.Location location = 2;</code>
       */
      public HotspotMessageProto.LocationOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_ == null ?
              HotspotMessageProto.Location.getDefaultInstance() : location_;
        }
      }
      /**
       * <code>.Location location = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          HotspotMessageProto.Location, HotspotMessageProto.Location.Builder, HotspotMessageProto.LocationOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              HotspotMessageProto.Location, HotspotMessageProto.Location.Builder, HotspotMessageProto.LocationOrBuilder>(
                  getLocation(),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }

      private double temperature_ ;
      /**
       * <code>double temperature = 3;</code>
       */
      public double getTemperature() {
        return temperature_;
      }
      /**
       * <code>double temperature = 3;</code>
       */
      public Builder setTemperature(double value) {
        
        temperature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double temperature = 3;</code>
       */
      public Builder clearTemperature() {
        
        temperature_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Hotspot)
    }

    // @@protoc_insertion_point(class_scope:Hotspot)
    private static final HotspotMessageProto.Hotspot DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HotspotMessageProto.Hotspot();
    }

    public static HotspotMessageProto.Hotspot getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Hotspot>
        PARSER = new com.google.protobuf.AbstractParser<Hotspot>() {
      public Hotspot parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Hotspot(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Hotspot> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Hotspot> getParserForType() {
      return PARSER;
    }

    public HotspotMessageProto.Hotspot getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DroneInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DroneInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Location location = 1;</code>
     */
    boolean hasLocation();
    /**
     * <code>.Location location = 1;</code>
     */
    HotspotMessageProto.Location getLocation();
    /**
     * <code>.Location location = 1;</code>
     */
    HotspotMessageProto.LocationOrBuilder getLocationOrBuilder();

    /**
     * <code>double heading = 2;</code>
     */
    double getHeading();
  }
  /**
   * Protobuf type {@code DroneInfo}
   */
  public  static final class DroneInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DroneInfo)
      DroneInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DroneInfo.newBuilder() to construct.
    private DroneInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DroneInfo() {
      heading_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DroneInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              HotspotMessageProto.Location.Builder subBuilder = null;
              if (location_ != null) {
                subBuilder = location_.toBuilder();
              }
              location_ = input.readMessage(HotspotMessageProto.Location.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(location_);
                location_ = subBuilder.buildPartial();
              }

              break;
            }
            case 17: {

              heading_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HotspotMessageProto.internal_static_DroneInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HotspotMessageProto.internal_static_DroneInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HotspotMessageProto.DroneInfo.class, HotspotMessageProto.DroneInfo.Builder.class);
    }

    public static final int LOCATION_FIELD_NUMBER = 1;
    private HotspotMessageProto.Location location_;
    /**
     * <code>.Location location = 1;</code>
     */
    public boolean hasLocation() {
      return location_ != null;
    }
    /**
     * <code>.Location location = 1;</code>
     */
    public HotspotMessageProto.Location getLocation() {
      return location_ == null ? HotspotMessageProto.Location.getDefaultInstance() : location_;
    }
    /**
     * <code>.Location location = 1;</code>
     */
    public HotspotMessageProto.LocationOrBuilder getLocationOrBuilder() {
      return getLocation();
    }

    public static final int HEADING_FIELD_NUMBER = 2;
    private double heading_;
    /**
     * <code>double heading = 2;</code>
     */
    public double getHeading() {
      return heading_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (location_ != null) {
        output.writeMessage(1, getLocation());
      }
      if (heading_ != 0D) {
        output.writeDouble(2, heading_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (location_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLocation());
      }
      if (heading_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, heading_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HotspotMessageProto.DroneInfo)) {
        return super.equals(obj);
      }
      HotspotMessageProto.DroneInfo other = (HotspotMessageProto.DroneInfo) obj;

      boolean result = true;
      result = result && (hasLocation() == other.hasLocation());
      if (hasLocation()) {
        result = result && getLocation()
            .equals(other.getLocation());
      }
      result = result && (
          java.lang.Double.doubleToLongBits(getHeading())
          == java.lang.Double.doubleToLongBits(
              other.getHeading()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLocation()) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocation().hashCode();
      }
      hash = (37 * hash) + HEADING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getHeading()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HotspotMessageProto.DroneInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HotspotMessageProto.DroneInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HotspotMessageProto.DroneInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HotspotMessageProto.DroneInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HotspotMessageProto.DroneInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HotspotMessageProto.DroneInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HotspotMessageProto.DroneInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HotspotMessageProto.DroneInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HotspotMessageProto.DroneInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HotspotMessageProto.DroneInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HotspotMessageProto.DroneInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HotspotMessageProto.DroneInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HotspotMessageProto.DroneInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DroneInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DroneInfo)
        HotspotMessageProto.DroneInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HotspotMessageProto.internal_static_DroneInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HotspotMessageProto.internal_static_DroneInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HotspotMessageProto.DroneInfo.class, HotspotMessageProto.DroneInfo.Builder.class);
      }

      // Construct using HotspotMessageProto.DroneInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (locationBuilder_ == null) {
          location_ = null;
        } else {
          location_ = null;
          locationBuilder_ = null;
        }
        heading_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HotspotMessageProto.internal_static_DroneInfo_descriptor;
      }

      public HotspotMessageProto.DroneInfo getDefaultInstanceForType() {
        return HotspotMessageProto.DroneInfo.getDefaultInstance();
      }

      public HotspotMessageProto.DroneInfo build() {
        HotspotMessageProto.DroneInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HotspotMessageProto.DroneInfo buildPartial() {
        HotspotMessageProto.DroneInfo result = new HotspotMessageProto.DroneInfo(this);
        if (locationBuilder_ == null) {
          result.location_ = location_;
        } else {
          result.location_ = locationBuilder_.build();
        }
        result.heading_ = heading_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HotspotMessageProto.DroneInfo) {
          return mergeFrom((HotspotMessageProto.DroneInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HotspotMessageProto.DroneInfo other) {
        if (other == HotspotMessageProto.DroneInfo.getDefaultInstance()) return this;
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        if (other.getHeading() != 0D) {
          setHeading(other.getHeading());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HotspotMessageProto.DroneInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HotspotMessageProto.DroneInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private HotspotMessageProto.Location location_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          HotspotMessageProto.Location, HotspotMessageProto.Location.Builder, HotspotMessageProto.LocationOrBuilder> locationBuilder_;
      /**
       * <code>.Location location = 1;</code>
       */
      public boolean hasLocation() {
        return locationBuilder_ != null || location_ != null;
      }
      /**
       * <code>.Location location = 1;</code>
       */
      public HotspotMessageProto.Location getLocation() {
        if (locationBuilder_ == null) {
          return location_ == null ? HotspotMessageProto.Location.getDefaultInstance() : location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>.Location location = 1;</code>
       */
      public Builder setLocation(HotspotMessageProto.Location value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
          onChanged();
        } else {
          locationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Location location = 1;</code>
       */
      public Builder setLocation(
          HotspotMessageProto.Location.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
          onChanged();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Location location = 1;</code>
       */
      public Builder mergeLocation(HotspotMessageProto.Location value) {
        if (locationBuilder_ == null) {
          if (location_ != null) {
            location_ =
              HotspotMessageProto.Location.newBuilder(location_).mergeFrom(value).buildPartial();
          } else {
            location_ = value;
          }
          onChanged();
        } else {
          locationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Location location = 1;</code>
       */
      public Builder clearLocation() {
        if (locationBuilder_ == null) {
          location_ = null;
          onChanged();
        } else {
          location_ = null;
          locationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Location location = 1;</code>
       */
      public HotspotMessageProto.Location.Builder getLocationBuilder() {
        
        onChanged();
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>.Location location = 1;</code>
       */
      public HotspotMessageProto.LocationOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_ == null ?
              HotspotMessageProto.Location.getDefaultInstance() : location_;
        }
      }
      /**
       * <code>.Location location = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          HotspotMessageProto.Location, HotspotMessageProto.Location.Builder, HotspotMessageProto.LocationOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              HotspotMessageProto.Location, HotspotMessageProto.Location.Builder, HotspotMessageProto.LocationOrBuilder>(
                  getLocation(),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }

      private double heading_ ;
      /**
       * <code>double heading = 2;</code>
       */
      public double getHeading() {
        return heading_;
      }
      /**
       * <code>double heading = 2;</code>
       */
      public Builder setHeading(double value) {
        
        heading_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double heading = 2;</code>
       */
      public Builder clearHeading() {
        
        heading_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DroneInfo)
    }

    // @@protoc_insertion_point(class_scope:DroneInfo)
    private static final HotspotMessageProto.DroneInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HotspotMessageProto.DroneInfo();
    }

    public static HotspotMessageProto.DroneInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DroneInfo>
        PARSER = new com.google.protobuf.AbstractParser<DroneInfo>() {
      public DroneInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DroneInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DroneInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DroneInfo> getParserForType() {
      return PARSER;
    }

    public HotspotMessageProto.DroneInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Location)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double latitude = 1;</code>
     */
    double getLatitude();

    /**
     * <code>double longitude = 2;</code>
     */
    double getLongitude();

    /**
     * <code>double altitude = 3;</code>
     */
    double getAltitude();
  }
  /**
   * Protobuf type {@code Location}
   */
  public  static final class Location extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Location)
      LocationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Location() {
      latitude_ = 0D;
      longitude_ = 0D;
      altitude_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Location(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              latitude_ = input.readDouble();
              break;
            }
            case 17: {

              longitude_ = input.readDouble();
              break;
            }
            case 25: {

              altitude_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HotspotMessageProto.internal_static_Location_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HotspotMessageProto.internal_static_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HotspotMessageProto.Location.class, HotspotMessageProto.Location.Builder.class);
    }

    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_;
    /**
     * <code>double latitude = 1;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <code>double longitude = 2;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    public static final int ALTITUDE_FIELD_NUMBER = 3;
    private double altitude_;
    /**
     * <code>double altitude = 3;</code>
     */
    public double getAltitude() {
      return altitude_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (latitude_ != 0D) {
        output.writeDouble(1, latitude_);
      }
      if (longitude_ != 0D) {
        output.writeDouble(2, longitude_);
      }
      if (altitude_ != 0D) {
        output.writeDouble(3, altitude_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (latitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, latitude_);
      }
      if (longitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, longitude_);
      }
      if (altitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, altitude_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HotspotMessageProto.Location)) {
        return super.equals(obj);
      }
      HotspotMessageProto.Location other = (HotspotMessageProto.Location) obj;

      boolean result = true;
      result = result && (
          java.lang.Double.doubleToLongBits(getLatitude())
          == java.lang.Double.doubleToLongBits(
              other.getLatitude()));
      result = result && (
          java.lang.Double.doubleToLongBits(getLongitude())
          == java.lang.Double.doubleToLongBits(
              other.getLongitude()));
      result = result && (
          java.lang.Double.doubleToLongBits(getAltitude())
          == java.lang.Double.doubleToLongBits(
              other.getAltitude()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLatitude()));
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLongitude()));
      hash = (37 * hash) + ALTITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAltitude()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HotspotMessageProto.Location parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HotspotMessageProto.Location parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HotspotMessageProto.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HotspotMessageProto.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HotspotMessageProto.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HotspotMessageProto.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HotspotMessageProto.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HotspotMessageProto.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HotspotMessageProto.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HotspotMessageProto.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HotspotMessageProto.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HotspotMessageProto.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HotspotMessageProto.Location prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Location)
        HotspotMessageProto.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HotspotMessageProto.internal_static_Location_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HotspotMessageProto.internal_static_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HotspotMessageProto.Location.class, HotspotMessageProto.Location.Builder.class);
      }

      // Construct using HotspotMessageProto.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        latitude_ = 0D;

        longitude_ = 0D;

        altitude_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HotspotMessageProto.internal_static_Location_descriptor;
      }

      public HotspotMessageProto.Location getDefaultInstanceForType() {
        return HotspotMessageProto.Location.getDefaultInstance();
      }

      public HotspotMessageProto.Location build() {
        HotspotMessageProto.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HotspotMessageProto.Location buildPartial() {
        HotspotMessageProto.Location result = new HotspotMessageProto.Location(this);
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        result.altitude_ = altitude_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HotspotMessageProto.Location) {
          return mergeFrom((HotspotMessageProto.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HotspotMessageProto.Location other) {
        if (other == HotspotMessageProto.Location.getDefaultInstance()) return this;
        if (other.getLatitude() != 0D) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0D) {
          setLongitude(other.getLongitude());
        }
        if (other.getAltitude() != 0D) {
          setAltitude(other.getAltitude());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HotspotMessageProto.Location parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HotspotMessageProto.Location) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double latitude_ ;
      /**
       * <code>double latitude = 1;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>double latitude = 1;</code>
       */
      public Builder setLatitude(double value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double latitude = 1;</code>
       */
      public Builder clearLatitude() {
        
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>double longitude = 2;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>double longitude = 2;</code>
       */
      public Builder setLongitude(double value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double longitude = 2;</code>
       */
      public Builder clearLongitude() {
        
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private double altitude_ ;
      /**
       * <code>double altitude = 3;</code>
       */
      public double getAltitude() {
        return altitude_;
      }
      /**
       * <code>double altitude = 3;</code>
       */
      public Builder setAltitude(double value) {
        
        altitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double altitude = 3;</code>
       */
      public Builder clearAltitude() {
        
        altitude_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Location)
    }

    // @@protoc_insertion_point(class_scope:Location)
    private static final HotspotMessageProto.Location DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HotspotMessageProto.Location();
    }

    public static HotspotMessageProto.Location getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Location>
        PARSER = new com.google.protobuf.AbstractParser<Location>() {
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Location(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Location> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    public HotspotMessageProto.Location getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FlightInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FlightInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string drone_name = 1;</code>
     */
    java.lang.String getDroneName();
    /**
     * <code>string drone_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getDroneNameBytes();

    /**
     * <code>uint32 flight_id = 2;</code>
     */
    int getFlightId();
  }
  /**
   * Protobuf type {@code FlightInfo}
   */
  public  static final class FlightInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FlightInfo)
      FlightInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FlightInfo.newBuilder() to construct.
    private FlightInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FlightInfo() {
      droneName_ = "";
      flightId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FlightInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              droneName_ = s;
              break;
            }
            case 16: {

              flightId_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HotspotMessageProto.internal_static_FlightInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HotspotMessageProto.internal_static_FlightInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HotspotMessageProto.FlightInfo.class, HotspotMessageProto.FlightInfo.Builder.class);
    }

    public static final int DRONE_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object droneName_;
    /**
     * <code>string drone_name = 1;</code>
     */
    public java.lang.String getDroneName() {
      java.lang.Object ref = droneName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        droneName_ = s;
        return s;
      }
    }
    /**
     * <code>string drone_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDroneNameBytes() {
      java.lang.Object ref = droneName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        droneName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLIGHT_ID_FIELD_NUMBER = 2;
    private int flightId_;
    /**
     * <code>uint32 flight_id = 2;</code>
     */
    public int getFlightId() {
      return flightId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDroneNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, droneName_);
      }
      if (flightId_ != 0) {
        output.writeUInt32(2, flightId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDroneNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, droneName_);
      }
      if (flightId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, flightId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HotspotMessageProto.FlightInfo)) {
        return super.equals(obj);
      }
      HotspotMessageProto.FlightInfo other = (HotspotMessageProto.FlightInfo) obj;

      boolean result = true;
      result = result && getDroneName()
          .equals(other.getDroneName());
      result = result && (getFlightId()
          == other.getFlightId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DRONE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getDroneName().hashCode();
      hash = (37 * hash) + FLIGHT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getFlightId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HotspotMessageProto.FlightInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HotspotMessageProto.FlightInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HotspotMessageProto.FlightInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HotspotMessageProto.FlightInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HotspotMessageProto.FlightInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HotspotMessageProto.FlightInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HotspotMessageProto.FlightInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HotspotMessageProto.FlightInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HotspotMessageProto.FlightInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HotspotMessageProto.FlightInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HotspotMessageProto.FlightInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HotspotMessageProto.FlightInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HotspotMessageProto.FlightInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FlightInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FlightInfo)
        HotspotMessageProto.FlightInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HotspotMessageProto.internal_static_FlightInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HotspotMessageProto.internal_static_FlightInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HotspotMessageProto.FlightInfo.class, HotspotMessageProto.FlightInfo.Builder.class);
      }

      // Construct using HotspotMessageProto.FlightInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        droneName_ = "";

        flightId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HotspotMessageProto.internal_static_FlightInfo_descriptor;
      }

      public HotspotMessageProto.FlightInfo getDefaultInstanceForType() {
        return HotspotMessageProto.FlightInfo.getDefaultInstance();
      }

      public HotspotMessageProto.FlightInfo build() {
        HotspotMessageProto.FlightInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HotspotMessageProto.FlightInfo buildPartial() {
        HotspotMessageProto.FlightInfo result = new HotspotMessageProto.FlightInfo(this);
        result.droneName_ = droneName_;
        result.flightId_ = flightId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HotspotMessageProto.FlightInfo) {
          return mergeFrom((HotspotMessageProto.FlightInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HotspotMessageProto.FlightInfo other) {
        if (other == HotspotMessageProto.FlightInfo.getDefaultInstance()) return this;
        if (!other.getDroneName().isEmpty()) {
          droneName_ = other.droneName_;
          onChanged();
        }
        if (other.getFlightId() != 0) {
          setFlightId(other.getFlightId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HotspotMessageProto.FlightInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HotspotMessageProto.FlightInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object droneName_ = "";
      /**
       * <code>string drone_name = 1;</code>
       */
      public java.lang.String getDroneName() {
        java.lang.Object ref = droneName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          droneName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string drone_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDroneNameBytes() {
        java.lang.Object ref = droneName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          droneName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string drone_name = 1;</code>
       */
      public Builder setDroneName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        droneName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string drone_name = 1;</code>
       */
      public Builder clearDroneName() {
        
        droneName_ = getDefaultInstance().getDroneName();
        onChanged();
        return this;
      }
      /**
       * <code>string drone_name = 1;</code>
       */
      public Builder setDroneNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        droneName_ = value;
        onChanged();
        return this;
      }

      private int flightId_ ;
      /**
       * <code>uint32 flight_id = 2;</code>
       */
      public int getFlightId() {
        return flightId_;
      }
      /**
       * <code>uint32 flight_id = 2;</code>
       */
      public Builder setFlightId(int value) {
        
        flightId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 flight_id = 2;</code>
       */
      public Builder clearFlightId() {
        
        flightId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FlightInfo)
    }

    // @@protoc_insertion_point(class_scope:FlightInfo)
    private static final HotspotMessageProto.FlightInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HotspotMessageProto.FlightInfo();
    }

    public static HotspotMessageProto.FlightInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FlightInfo>
        PARSER = new com.google.protobuf.AbstractParser<FlightInfo>() {
      public FlightInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FlightInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FlightInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FlightInfo> getParserForType() {
      return PARSER;
    }

    public HotspotMessageProto.FlightInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Hotspot_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Hotspot_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DroneInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DroneInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Location_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Location_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FlightInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FlightInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025hotspot_message.proto\"[\n\007Hotspot\022\036\n\ndr" +
      "one_info\030\001 \001(\0132\n.DroneInfo\022\033\n\010location\030\002" +
      " \001(\0132\t.Location\022\023\n\013temperature\030\003 \001(\001\"9\n\t" +
      "DroneInfo\022\033\n\010location\030\001 \001(\0132\t.Location\022\017" +
      "\n\007heading\030\002 \001(\001\"A\n\010Location\022\020\n\010latitude\030" +
      "\001 \001(\001\022\021\n\tlongitude\030\002 \001(\001\022\020\n\010altitude\030\003 \001" +
      "(\001\"3\n\nFlightInfo\022\022\n\ndrone_name\030\001 \001(\t\022\021\n\t" +
      "flight_id\030\002 \001(\rB\025B\023HotspotMessageProtob\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Hotspot_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Hotspot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Hotspot_descriptor,
        new java.lang.String[] { "DroneInfo", "Location", "Temperature", });
    internal_static_DroneInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DroneInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DroneInfo_descriptor,
        new java.lang.String[] { "Location", "Heading", });
    internal_static_Location_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Location_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "Altitude", });
    internal_static_FlightInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_FlightInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FlightInfo_descriptor,
        new java.lang.String[] { "DroneName", "FlightId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
